email:
  imap_server: "imap.gmail.com"
  email_address: "ssaemailagentai@gmail.com"
  password: "jews kwwa axmz yztx"

mysql:
  host: "localhost"
  user: "root"
  password: "root"
  database: "email_automation"
